# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88021500574d3b498be0239350f5cf517215a8aa6f300201bbdfcff7c537b79b5ce323f522e6f02d2adb22b39a0237f2fd9d38658ab81035068efb20bbad4d00

test:
  secret_key_base: dda8a6937998aebb59bf589abdaccaadfdd6fbe180f98da5cf02c6d80ba7acbebb9ffc40e424f605f562d1bed3a0bce29fb6f70d79ecc78c19d45787b37da3c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
